config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  resources :courses do
    resources :lessons
    resource :quiz
  end

  resources :likes, only: [:create, :destroy]

  devise_for :users

  # Defines the root path route ("/")
  root  'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :lessons
  has_many :likes
  has_one :quiz
  has_many_attached :images
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
   belongs_to :course
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: :course_id}
  belongs_to :user
  belongs_to :course
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :likes
  has_many :favorite_courses, source: :course, through: :likes #userslikes

  VALID_ROLES = %w[student admin instructor]
  validates :role, inclusion: { in: VALID_ROLES }

  before_validation :default_role
  def default_role
     self.role = :student
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
  def show
    @course=Course.where(id:params[:id]).first
    unless @course.present?
      redirect_to("/")
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params)
      redirect_to @course
    else
      render :edit, status: :unprocessable_entity
    end
  end

   def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to root_path, status: :see_other
  end


   private
    def course_params
      params.require(:course).permit(:title, :body, images: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'

url =  URI.parse('https://tenor.googleapis.com/v2/search?q=excited&key=AIzaSyAixkfivBOP0SRhjMe2QjtX7qhLe-cALqk&client_key=my_test_app&limit=8')
req = Net::HTTP::Get.new url
res = Net::HTTP.start(url.host, url.port,
        :use_ssl => url.scheme == 'https') {|http| http.request req}

    @gifs = JSON.parse(res.body) #hash

  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
   def create
    @course = Course.find(params[:course_id])
    @lesson = @course.lessons.create(lesson_params)
    redirect_to course_path(@course)
   end

   def show
    @lesson = Lesson.find(params[:id])
   end

   def new
     @lesson = Lesson.new(course_id: params[:course_id])
   end

   def edit
     @lesson = Lesson.find(params[:id])
   end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update(lesson_params)
      redirect_to course_path(@lesson.course)
    else
      render :edit, status: :unprocessable_entity
    end
  end

    def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def lesson_params
      params.require(:lesson).permit(:title, :body, :video_url)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.new(like_params)
    unless @like.save
      flash[:notice] = "You can't like more than once"
    end
    redirect_to courses_path
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @course = @like.course
    @like.destroy
    redirect_to courses_path
  end

  private
  def like_params
    params.require(:like).permit(:course_id)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_course, only: [:show, :new, :create, :edit, :update, :destroy]

  def show
    @quiz = @course.quiz
  end

  def new
    @quiz = @course.quiz
  end

  def create
    @quiz = @course.build_quiz(quiz_params)
    if @quiz.save
      redirect_to quiz_params, notice: 'Quiz created successfully.'
    else
      render :new
    end
  end

  def edit
    @quiz = @course.quiz
  end

  def update
    @quiz = @course.quiz
    if @quiz.update(quiz_params)
      redirect_to quiz_params, notice: 'Quiz updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @quiz = @course.quiz
    @quiz.destroy
    redirect_to @course, notice: 'Quiz deleted successfully.'
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def quiz_params
    params.require(:quiz).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/courses/_form.html.erb
<%= form_with model: course do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% course.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% course.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render "form", course: @course %>

app/views/courses/index.html.erb
<h1>Courses</h1>
<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course do %>
        <% if course.images.attached? %>
          <% course.images.each do |image| %>
            <%= image_tag image, {height: "80px", class: "nav-link", style: "border-radius: 5px;"} %>
          <% end %>
        <% end %>
         <%= course.title %>
      <% end %>


        <br>
       Likes: <%= course.likes.count %>
     <% like = current_user.likes.find_by(course: course) %>
      <% if like.nil? %>
        <form action="/likes" method="post">
           <input type ="hidden" name="authenticity_token" value="<%=form_authenticity_token %> "/>
           <input type ="hidden" name="like[course_id]" value="<%= course.id %> "/>
           <input type="submit" value="Like"/>
        </form>
      <% else %>
        <form action="<%= like_path(like) %>" method="post">
           <input type ="hidden" name="authenticity_token" value="<%=form_authenticity_token %> "/>
           <input type="hidden" name="_method" value="DELETE">
           <input type="submit" value="Unlike"/>
        </form>
      <% end %>
    </li>

    <% if course.quiz.nil? %>
        <li><%= link_to "Add QUIZ", new_course_quiz_path(course) %></li>
      <% else %>
        <li><%= link_to "Get QUIZ", course_quiz_path(course) %></li>
      <% end %>


    <br>
    <br>
  <% end %>
</ul>
<%= link_to "New Course", new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= form_with model: @course do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
     <% @course.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
     <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
     <% @course.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
     <% end %>
  </div>

  <div>
    <%= form.label :video_url %><br>
    <%= form.text_area :video_url %>
     <% @course.errors.full_messages_for(:video_url).each do |message| %>
      <div><%= message %></div>
     <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/show.html.erb
 <h1>Course: <%= @course.title %></h1>


<li><%= link_to "Edit", edit_course_path(@course) %></li>
   <li><%= link_to "Destroy", course_path(@course), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>
<h3>About course: </h3><p><%= @course.body %></p>

<h3>Lessons</h3>
<ul>
  <%= render @course.lessons %>
</ul>

 <%= link_to "New Lesson", new_course_lesson_path(@course) %>

app/views/courses/show.json.erb
<%= raw(@course.to_json)   %>

app/views/home/index.html.erb
<h1>Salem, sen roottasyn!</h1>
<p>Find me in app/views/home/index.html.erb</p>

<!--<img src="<%#= @gifs["reysults"][0]["media_formats"][ "mediumgif"]["url"] %>">-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eduverse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Eduverse</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "COURSES", courses_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Language
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Kazakh</a></li>
                <li><a class="dropdown-item" href="#">English</a></li>
                <li><a class="dropdown-item" href="#">Turkish</a></li>
                <li><hr class="dropdown-divider"></li>

              </ul>
            </li>

          </ul>
          <form class="d-flex  me-auto mb-2 mb-lg-0" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          <ul class="navbar-nav">
              <% if current_user %>
                <%# if current_user.avatar.attached? %>
                  <li class="nav-item">
                    <%#= image_tag current_user.avatar, class: "nav-link avatar-mini-circle" %>
                  </li>
                <%# end %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= current_user.email %>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
                     <li><%#= link_to "My courses", user_cars_path, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <div class="container-sm">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with model: [@lesson.course, @lesson]  do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @lesson.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @lesson.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :video_url %><br>
    <%= form.text_area :video_url %><br>
    <% @lesson.errors.full_messages_for(:video_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<li>
<%= link_to lesson.title, course_lesson_path(@course, lesson) %>
</li>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>
<%= render 'form'%>

app/views/lessons/new.html.erb
<h1>Add Lesson</h1>
<%= render 'form'%>

app/views/lessons/show.html.erb
<h1><%= @lesson.title %></h1>

<p><%= @lesson.body %></p>
<iframe width="560" height="315" src="<%= @lesson.video_url %>" allow="autoplay; encrypted-media" allowfullscreen></iframe>
<ul>
  <li><%= link_to "Edit", edit_course_lesson_path(@lesson.course, @lesson) %></li>
   <li><%= link_to "Destroy", course_lesson_path(@lesson.course, @lesson), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/quizzes/_form.html.erb
<%= form_with model: @quiz, url: course_quiz_path(@course), local: true do |form| %>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @quiz.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Edit Quiz</h1>
<%= render 'form'%>

app/views/quizzes/new.html.erb
<h1>Add a question</h1>
<%= render 'form'%>

app/views/quizzes/show.html.erb
<h2>Quiz of course "<%= @course.title %>"</h2>

<%= link_to "Edit QUIZ", edit_course_quiz_path(@course) %>
<br>
<br>

<form>
  <% bodyHash = eval(@quiz.body) %>
  <% bodyHash[:questions].each_with_index do |q, questionIndex| %>
    <b>Question <%= questionIndex + 1 %>:</b>
    <br>
    <i><%= q[:question] %></i>
    <br>
    <% q[:array_options].each_with_index do |op, optionIndex| %>
      <% optionId = questionIndex.to_s + ":" + optionIndex.to_s %>
      <label for="inputradio-<%= questionIndex %>"><%= op[:option_text] %></label>
      <input type="radio" name="inputradio-<%= questionIndex %>" value="<%= optionId %>" />
      <br>
    <% end %>
    <br>
  <% end %>

  <button type="submit" onclick="Submit()">submit</button>

</form>

 <script>
        const all = <%= bodyHash[:questions].count %>;
        const bodyJson = <%= raw(bodyHash.to_json) %>;

        function Submit() {
            let correct = 0;
            const radioInputs = document.querySelectorAll('input[type="radio"]:checked');
            radioInputs.forEach((input) => {
                let questionIndex = input.value.split(":")[0];
                let optionIndex = input.value.split(":")[1];
                if (bodyJson["questions"][questionIndex]["array_options"][optionIndex]["correct"]) {
                    correct++;
                }
            });
            alert("Your score: " + correct + "/" + all)
            return false;
        }
</script>